name: Deployment

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: kult.cash
          username: kultursp
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            cd /var/www/virtual/kultursp/kult.cash/
            ./deploy.sh
